services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"  
      
  manaworkscandidate:
    image: manaworkscandidate
    build:
      context: .
      dockerfile: ManaWorksCandidate/Dockerfile

